"""creating traffic table

Revision ID: 53d0d1a62ca1
Revises: 
Create Date: 2026-09-17 12:54:40.999868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53d0d1a62ca1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traffic_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('sensor_773869', sa.Float(), nullable=False),
    sa.Column('sensor_773906', sa.Float(), nullable=False),
    sa.Column('sensor_718204', sa.Float(), nullable=False),
    sa.Column('sensor_773927', sa.Float(), nullable=False),
    sa.Column('sensor_773953', sa.Float(), nullable=False),
    sa.Column('sensor_773916', sa.Float(), nullable=False),
    sa.Column('sensor_717572', sa.Float(), nullable=False),
    sa.Column('sensor_718090', sa.Float(), nullable=False),
    sa.Column('sensor_718496', sa.Float(), nullable=False),
    sa.Column('sensor_773904', sa.Float(), nullable=False),
    sa.Column('sensor_761003', sa.Float(), nullable=False),
    sa.Column('sensor_774204', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_data_timestamp'), 'traffic_data', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traffic_data_timestamp'), table_name='traffic_data')
    op.drop_table('traffic_data')
    # ### end Alembic commands ###
